version: '3.9'
name: ${COMPOSE_PROJECT_NAME}

volumes:
  node_modules: {}

services:
  nuxt:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_local_nuxt
    container_name: ${COMPOSE_PROJECT_NAME}_local_nuxt
    env_file: .env
    ports:
      - '0.0.0.0:3018:3000'
      - '0.0.0.0:24678:24678'
    command: yarn dev  # sh -c "yarn && yarn dev"
    volumes:
      - .:/nuxt
      - node_modules:/nuxt/node_modules
    labels:
      - "traefik.enable=false"
