version: '3.9'
name: ${COMPOSE_PROJECT_NAME}

volumes:
  node_modules: {}

services:
  nuxt:
    build:
      context: .
      dockerfile: ./compose/local/Dockerfile
    image: ${COMPOSE_PROJECT_NAME}_local_nuxt
    container_name: ${COMPOSE_PROJECT_NAME}_local_nuxt
    restart: unless-stopped
    env_file: .env
    environment:
      - HMR_PROTOCOL=ws
      - PROTOCOL=http
    ports:
      - '${NUXT_DOCKER_PORT}:3000'
      - '${HMR_DOCKER_PORT}:24678'
    command: yarn dev  # sh -c "yarn && yarn dev"
    volumes:
      - .:/nuxt
      - node_modules:/nuxt/node_modules
